spring.application.name=portfolio
server.servlet.context-path=/flexitechmm
server.port=80

# Thymeleaf Cache Configuration
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML

# Logging levels
logging.level.org.flexitech.projects.ecommerce=DEBUG
logging.level.org.springframework=INFO
logging.level.org.hibernate=WARN

# Log file
logging.file.name=D:/logs/portfolio/admin/admin.log

# Pattern
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n


#image path
image.path=D:/FlexiTech/Company Data/Projects/itech-mm/images/portfolio
image.context.path=/
image.zip.upload.path=D:/FlexiTech/Company Data/Projects/itech-mm/images/portfolio/upload

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB


#messages
spring.messages.basename=messages
spring.messages.encoding=UTF-8

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=itech.saizawmyint@gmail.com
spring.mail.password=bnqewkgydfwlruep
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Set the receiving team email address here
app.team.email=itech.saizawmyint@gmail.com